### ISSUE TITLE
Submit failed for all browsers

### ISSUE THREAD

**Issue by Armaldio** [LinusU/wext-shipit#2]
<details>
  <summary>EDIT: Chrome now works</summary>
Chrome failed with: 
```
Response code 400 (Bad Request)
{
    "error": "invalid_request",
    "error_description": "Parameter not allowed for this message type: redirect_uri"
}
Error: Command failed: D:\Projects\ConstructAddonInstaller\Installer\node_modules\@wext\shipit\node_modules\.bin\webstore upload --source BrowserExtension --extension-id xxx --client-id xxx --client-secret xxx --refresh-token xxx --auto-publish
``` 
</details>

<br>

Firefox failed with: 
```
× Error: Failed to submit extension to addons.mozilla.org
```
(all other steps are successfull)

Opera failed with:
```
× Error: waiting failed: timeout 30000ms exceeded
```

**Comment by LinusU** [comment]
Hey, sorry for the delay in getting back to you on this.

Regarding Opera, could you try running it with `DEBUG_UPLOAD_OPERA_EXTENSION=1` set in the environment? That should show a Chrome window that tries to submit the extension, and from there we should be able to see where it gets stuck.

Regarding Firefox, the error indicates that the string `Your add-on has been submitted for review.` wasn't printed to stdout during the firefox tool execution. Could you try running the following command manually? Note that _it will always fail_, that is one of the things that @wext/shipit works around. But if it "worked", it should print the before mentioned string.

```sh
web-ext sign --source-dir <source-dir> --api-key $WEXT_SHIPIT_FIREFOX_JWT_ISSUER --api-secret $WEXT_SHIPIT_FIREFOX_JWT_SECRET
```

Regarding Chrome, what did you do to make it work? I'd be happy to take steps to implement better error messages and tips on how to move forward 🙌

**Comment by Armaldio** [comment]
So I tried sumitting a new version today.
Nevermind with Opera for now, I think the error is because my previous version is not yet approved.

<details>
<summary>About firefox, I still can't make it work. Now I get:</summary>
$ shipit firefox BrowserExtension
\ Building extension...Server response: Version already exists. (status: 409)
× Error: Command failed: D:\Projects\ConstructAddonInstaller\Installer\node_modules\@wext\shipit\node_modules\.bin\web-ext sign --source-dir BrowserExtension --api-key user:13822079:21 --api-secret 1a977c386cced1018079367a2aa2ec0ebba921380dce194e51c65b347784056b
Building web extension from D:\Projects\ConstructAddonInstaller\Installer\BrowserExtension
Using previously auto-generated extension ID: {f0039c12-d785-4cf5-9504-a23f44f77996}
FAIL

WebExtError: The extension could not be signed
    at _callee$ (D:\Projects\ConstructAddonInstaller\Installer\node_modules\web-ext\dist\webpack:\src\cmd\sign.js:134:15)
    at tryCatch (D:\Projects\ConstructAddonInstaller\Installer\node_modules\web-ext\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\Projects\ConstructAddonInstaller\Installer\node_modules\web-ext\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\Projects\ConstructAddonInstaller\Installer\node_modules\web-ext\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\Projects\ConstructAddonInstaller\Installer\node_modules\web-ext\dist\webpack:\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:1)
    at D:\Projects\ConstructAddonInstaller\Installer\node_modules\web-ext\dist\webpack:\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)


Error: Command failed: D:\Projects\ConstructAddonInstaller\Installer\node_modules\@wext\shipit\node_modules\.bin\web-ext sign --source-dir BrowserExtension --api-key user:13822079:21 --api-secret 1a977c386cced1018079367a2aa2ec0ebba921380dce194e51c65b347784056b
Building web extension from D:\Projects\ConstructAddonInstaller\Installer\BrowserExtension
Using previously auto-generated extension ID: {f0039c12-d785-4cf5-9504-a23f44f77996}
FAIL

WebExtError: The extension could not be signed
    at _callee$ (D:\Projects\ConstructAddonInstaller\Installer\node_modules\web-ext\dist\webpack:\src\cmd\sign.js:134:15)
    at tryCatch (D:\Projects\ConstructAddonInstaller\Installer\node_modules\web-ext\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\Projects\ConstructAddonInstaller\Installer\node_modules\web-ext\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (D:\Projects\ConstructAddonInstaller\Installer\node_modules\web-ext\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (D:\Projects\ConstructAddonInstaller\Installer\node_modules\web-ext\dist\webpack:\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:1)
    at D:\Projects\ConstructAddonInstaller\Installer\node_modules\web-ext\dist\webpack:\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)


    at makeError (D:\Projects\ConstructAddonInstaller\Installer\node_modules\@wext\shipit\node_modules\execa\index.js:169:9)
    at Promise.all.then.arr (D:\Projects\ConstructAddonInstaller\Installer\node_modules\@wext\shipit\node_modules\execa\index.js:274:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
error Command failed with exit code 1.
</details>


About chrome, what I did is just waiting before the previous extension was approved AND launching the command from a separated command prompt (the one integrated inside my IDE never worked)

**Comment by LinusU** [comment]
> Nevermind with Opera for now, I think the error is because my previous version is not yet approved.

I don't think so, not a single of my versions are approved, and I have submitted quite a few using this tool 😆 it seems like they are super slow on reviewing 😞 

> Server response: Version already exists. (status: 409)

Did you bump the version in your manifest? It seems to think that that version is already uploaded.

I can recommend generating the version using this package: https://www.npmjs.com/package/utc-version

**Comment by Armaldio** [comment]
Yeah they review manually. When it's approved first, it's super slow but it seems better once your have it accepted for the first time

My bad, I couldn't separate the log between FF and Opera so I done it again using FF to have a clear log ^^

Here is the real log: https://hastebin.com/apitunufum.tex
I get the e-mail saying that my version passeed the tests but it never upload to the store

**Comment by LinusU** [comment]
Hmm, that's interesting, could you try running the following command? If this gives an error as well, we'll probably need to raise an issue with the [web-ext](https://github.com/mozilla/web-ext) tool

```sh
web-ext sign --source-dir BrowserExtension --api-key $WEXT_SHIPIT_FIREFOX_JWT_ISSUER --api-secret $WEXT_SHIPIT_FIREFOX_JWT_SECRET
```

It probably will, since that is pretty much what this tool invoked. Would you mind opening an issue here: [web-ext](https://github.com/mozilla/web-ext)

**Comment by Armaldio** [comment]
Yeah it gives an error as well.. https://hastebin.com/ajurokanop.tex
I found an issue similar to mine: https://github.com/mozilla/web-ext/issues/1111
